name: Check links

permissions:
  contents: read
  pull-requests: write

on:
  push:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: tcort/github-action-markdown-link-check@v1
        with:
          config-file: .markdown-link-check.json
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
