name: test
on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'

    - run: npm ci

    - run: npm test
