name: test
on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'

    - run: npm ci

    - run: FORCE_COLOR=2 IGNORE_EXTERNAL_LINK_CHECKING=${{ secrets.IGNORE_EXTERNAL_LINK_CHECKING }} npm test
