name: test
on: push

permissions:
  contents: read
  pull-requests: write

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: tcort/github-action-markdown-link-check@v1.1.0

  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - run: npm ci

    - run: FORCE_COLOR=2 IGNORE_EXTERNAL_LINK_CHECKING=${{ secrets.IGNORE_EXTERNAL_LINK_CHECKING }} npm test
